version: "3"
services:
  api:
    image: guiliuimage:1.0.0
    environment:
      SLEEP_LENGTH: 5
      POSTGRES_HOST: db
      POSTGRES_USER: guiliu
      POSTGRES_PASSWORD: 525261
      POSTGRES_DB: record
    ports:
      - 8080:8080
    depends_on:
      - "db"
  db:
    image: postgres
    environment:
      POSTGRES_USER: guiliu
      POSTGRES_PASSWORD: 525261
      POSTGRES_DB: record
